export declare class Color {
    static white: Color;
    static black: Color;
    static gray: Color;
    static light_gray: Color;
    static yellow: Color;
    static ocher: Color;
    static orange: Color;
    static brown: Color;
    static red: Color;
    static dark_red: Color;
    static pink: Color;
    static magenta: Color;
    static light_purple: Color;
    static purple: Color;
    static indigo: Color;
    static dark_indigo: Color;
    static blue: Color;
    static dark_blue: Color;
    static agua: Color;
    static dark_agua: Color;
    static cyan: Color;
    static dark_cyan: Color;
    static mint: Color;
    static jade: Color;
    static light_green: Color;
    static green: Color;
    static lime: Color;
    static avocado: Color;
    r: number;
    g: number;
    b: number;
    constructor(r: number, g: number, b: number);
}
